// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "This is a calculator!");
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* displayValue */"",
              /* currentOperator : None */0,
              /* currentValue */0.0
            ];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* NoUpdate */0;
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
