// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Buttons");

function renderButtons() {
  return React.createElement("div", undefined, $$Array.of_list(List.map((function (button) {
                        return React.createElement("button", undefined, button);
                      }), /* :: */[
                      "0",
                      /* :: */[
                        "1",
                        /* :: */[
                          "2",
                          /* :: */[
                            "3",
                            /* :: */[
                              "4",
                              /* :: */[
                                "5",
                                /* :: */[
                                  "6",
                                  /* :: */[
                                    "7",
                                    /* :: */[
                                      "8",
                                      /* :: */[
                                        "9",
                                        /* :: */[
                                          "+",
                                          /* :: */[
                                            "-",
                                            /* :: */[
                                              "/",
                                              /* :: */[
                                                "*",
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ])));
}

function make(onClick, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return renderButtons(onClick);
    });
  return newrecord;
}

exports.component     = component;
exports.renderButtons = renderButtons;
exports.make          = make;
/* component Not a pure module */
